### ISSUE TITLE
[JOSS review] Minor installation issue

### ISSUE THREAD

**Issue by MoLi7** [Mat-dp/mat-dp-core#22]
In your [installation instruction](https://github.com/Mat-dp/mat-dp-core#installation-and-launch), please clarify whether users need to clone your repo or `pip install` the software in order to launch the model.

https://github.com/openjournals/joss-reviews/issues/4460

**Comment by kcerva** [comment]
Hi @MoLi7 we have now added mat-dp-core to PyPi and have therefore modified the instructions to say that the user can install the library using pip.

**Comment by MoLi7** [comment]
Awesome. Thanks!
